---
- name: system config for rpi-statusscreen
  hosts: localhost
  connection: local
  gather_facts: false
  become_user: root
  become: yes

  tasks:

    - name: enable spi
      ansible.builtin.lineinfile:
        path: /boot/config.txt
        line: 'dtparam=spi=on'
        create: yes

    - name: enable i2c
      ansible.builtin.lineinfile:
        path: /boot/config.txt
        line: 'dtparam=i2c_arm=on'
        create: yes

    - name: install packages
      ansible.builtin.apt:
        pkg:
          - python3-pip
          - python3-pillow
          - python3-smbus 
          - silversearcher-ag

    - name: pip install epdlib
      ansible.builtin.pip:
        name: epdlib
        extra_args: --break-system-packages

